version: '3.8'

services:
  link-study-backend:
    build: ./backend
    ports: 
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    restart: on-failure
    
  link-study-frontend:
    build: ./frontend
    ports: 
      - "4200:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - link-study-backend
    restart: on-failure